//! sr-telegram: Telegram notification bot for the School Run Strategy.
//!
//! This crate provides a Telegram bot that notifies subscribers about
//! trading signals generated by the sr-engine. Users can subscribe to
//! specific instruments and receive real-time notifications when signal
//! bars form, orders trigger, and trades close.

pub mod commands;
pub mod config;
pub mod error;
pub mod notifications;
pub mod signals;
pub mod store;
